server:
  undertow:
    io-threads: 2
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
  port: 8081
spring:
  profiles:
    active: pro
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: classpath:/static/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#TOKEN工具
jwt:
  header: Authorization
  secret: mysecret
  expiration: 604800
  tokenHead: "cat "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "/api/users/actions/register"

